#!/usr/bin/env bash

# Script mostly generated by GH Copilot.

# Fail the script if a command fails or a variable is unset.
# Note that grep will fail (exit 1) if it finds no matches, but we don't want the pipe to fail.
set -eu
# Show command execution
set -x

new_py=3.14
tmp_env="tmp"

# for 27J, add pair M279:M269 in 2nd position
replacements=(
  "25:26"
	"3\\.12\\.10:${new_py}.6"
	"3\\.12:${new_py}"
)

for pair in "${replacements[@]}"; do
	IFS=':' read -r from to <<< "$pair"

  # Copilot: grep ... | xargs sed ... is less robust if grep returns nothing or spaces in filenames
	grep -RIl --exclude-dir=.git --exclude-dir=$tmp_env --exclude=requirements.txt --exclude=new_year.sh -- "$from" . |
	while IFS= read -r file; do
		sed -i '' "s/${from}/${to}/g" "$file"
	done
done

if ! command -v "python${new_py}" &> /dev/null; then
	echo "Python ${new_py} is not installed. Please install it and try again."
    exit 1
fi

python${new_py} -m venv --clear "$tmp_env"
source "$tmp_env/bin/activate"
pip install --upgrade pip
pip install jupyterlab matplotlib networkx jupyterlab-rise rise allowed algoesup ruff python_ta paddles
pip check
pip freeze > requirements.txt
deactivate
