#!/usr/bin/env bash

# Script mostly generated by GH Copilot. Doesn't use xargs, saying it's less robust.

# Fail the script if a command fails, if a variable is unset, or if a command in a pipeline fails.
set -euo pipefail

# for 27J, add pair M279:M269 in 2nd position
replacements=(
  "25:26"
  "3\\.12\\.10:3.14.6"
  "3\\.12:3.14"
)

for pair in "${replacements[@]}"; do
	IFS=':' read -r from to <<< "$pair"

	grep -RIl --exclude-dir=.git --exclude=requirements.txt --exclude=new_year.sh -- "$from" . |
	while IFS= read -r file; do
		sed -i '' "s/${from}/${to}/g" "$file"
	done
done
